spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:yelog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  sql:
    init-model: always

yelog:
  jwt-key: "4+rwsQ2gJvu0yrkdJnwftn9o30Das9vy4XpI9+t2G3M="
