### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=dldpcks34@naver.com&password=1234&remember=1

### 회원가입

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name" : "이예찬",
  "email" : "dldpcks34@naver.com",
  "password" : "1234"
}


### 메인페이지

GET  http://localhost:8080
