### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=yechan&password=1234

### 인증페이지 요청

GET  http://localhost:8080/foo
Content-Type: application/json
Cookie: SESSION=ca8471b5-116d-4996-9984-ab2d4278bb92